BLUEZ_SERVICE_NAME = 'org.bluez'

ADAPTER_IFACE = BLUEZ_SERVICE_NAME + '.Adapter1'
DEVICE_IFACE = BLUEZ_SERVICE_NAME + '.Device1'
GATT_MANAGER_IFACE = BLUEZ_SERVICE_NAME + '.GattManager1'
LE_ADVERTISING_MANAGER_IFACE = BLUEZ_SERVICE_NAME + '.LEAdvertisingManager1'
LE_ADVERTISEMENT_IFACE = BLUEZ_SERVICE_NAME + '.LEAdvertisement1'

GATT_SERVICE_IFACE = BLUEZ_SERVICE_NAME + '.GattService1'
GATT_CHRC_IFACE =    BLUEZ_SERVICE_NAME + '.GattCharacteristic1'
GATT_DESC_IFACE =    BLUEZ_SERVICE_NAME + '.GattDescriptor1'

DBUS_OM_IFACE =      'org.freedesktop.DBus.ObjectManager'
DBUS_PROP_IFACE =    'org.freedesktop.DBus.Properties'